### ISSUE TITLE
Error in console + doesn't working plugin

### ISSUE THREAD

**Issue by bobhenl** [Phoenix616/AutoQueue#1]
#### Used Version

 https://ci.minebench.de/job/AutoQueue/16/
 [04:15:13] [main/INFO]: Loaded plugin AutoQueue version 1.0-SNAPSHOT (build 16) by Phoenix616

#### Config

 ```yaml
default-locale: en
# Automatically enter the player into a queue to join a server when joining
# Usefull if you want to put a void server as a queue in front of your main one
# Leave empty/invalid if you don't want that
login-queue:
  # Delay between joins
  delay: 500
  # The target server to send the player to
  target:
  - Lobby
  # Optional: Only start this queue once there is this amount of players on the target server
  target-amount: 1
switch-queues:
  examplequeue:
    # Delay between joins in milliseconds
    delay: 500
    # Optional: Maximum amount of players that can be in this queue at the same time
    max-size: 50
    # Optional: Source server list
    source:
    - Lobby
    # Optional: Target server list
    # Automatically triggers when player tries to switch from any source server to any target server
    target:
    - Survival
    - Svanilla
    - Build
    - Dev
    - MobArena
    - MurderMystery
    - HungerGames
    - Paintball
    # Optional: Only start this queue once there is this amount of players on the target server
    target-min-amount: 1
    # Optional: Only allow joining via the queue up to this many players on the target server
    target-max-amount: 50
    # Optional: The ServerConnectEvent.Reason for this server switch
    connect-reason:
    - COMMAND
    - PLUGIN_MESSAGE
    - PLUGIN
    - UNKNOWN
 ```
 
#### Environment description

 Debian Server 10 64bit
Default language
Version: Waterfall 379 
 
#### Full Log

Is so large... I tried to put it here, but it didn't work, so I put it on another place.  EDIT: File is so large, can't be on Pastebin, Hastebin, anywhere...
[2020-10-14-2.log.gz](https://github.com/Phoenix616/AutoQueue/files/5381689/2020-10-14-2.log.gz)

#### What other programs/plugins are you running?

You can see in log? https://imgur.com/f6qcXNQ and https://imgur.com/NEkHCg1

#### What is happening?

There is appearing error from your plugin and the plugin doesn't seems working. Is the configuration correct?

#### What did you expect to happen?

 I want that players can join queue from Lobby to another servers - Survival, Semi (I know the other ones aren't detected, cause they wren't enabled still).

#### Additional context

Nothing important.
